"""
Enzyme Feature Calculation - TOMER-Based Feature Engineering
============================================================
This script calculates protein features for enzymes in CSV files
generated by query_brenda.py using the 'enzyme_feature_lib' library.

Usage:
    python calculate_enzyme_features.py enzyme_data.csv -o enzyme_features.csv

Requirements:
    - enzyme_feature_lib.py (must be in the same directory)
    - pandas
"""

import pandas as pd
import argparse
import sys
import enzyme_feature_lib as elib  # Import our custom feature library

def load_csv(file_path):
    """
    Loads CSV file (query_brenda.py output).
    Supports both ; and , delimiters.
    """
    # First try ; delimiter
    try:
        df = pd.read_csv(file_path, sep=';')
        if 'sequence' in df.columns:
            print(f"File read (delimiter: ;). {len(df)} records found.")
            return df
    except:
        pass

    # Then try , delimiter
    try:
        df = pd.read_csv(file_path, sep=',')
        if 'sequence' in df.columns:
            print(f"File read (delimiter: ,). {len(df)} records found.")
            return df
    except:
        pass

    print(f"Error: Could not read {file_path} or 'sequence' column not found.")
    sys.exit(1)


def print_summary(df, result_df):
    """Prints feature summary."""
    # Find newly added columns
    feature_cols = [c for c in result_df.columns if c not in df.columns]
    features_df = result_df[feature_cols]

    # Count feature categories
    aa_features = len([c for c in features_df.columns if c.startswith('aa_')])
    group_features = len([c for c in features_df.columns if c.startswith('group_')])
    dp_features = len([c for c in features_df.columns if c.startswith('dp_')])
    
    basic_features = ['length', 'molecular_weight', 'gravy', 'aromaticity', 
                      'instability_index', 'isoelectric_point',
                      'charge_pH4', 'charge_pH7', 'charge_pH10', 'charge_density',
                      'extinction_reduced', 'extinction_oxidized',
                      'helix_fraction', 'turn_fraction', 'sheet_fraction']
    basic_count = len([c for c in basic_features if c in features_df.columns])
    
    thermo_features = ['aliphatic_index', 'boman_index', 'farias_bonato_ratio',
                       'arg_lys_ratio', 'acidic_basic_ratio']
    thermo_count = len([c for c in thermo_features if c in features_df.columns])
    
    flex_features = ['flexibility_mean', 'flexibility_std', 
                     'flexibility_max', 'flexibility_min']
    flex_count = len([c for c in flex_features if c in features_df.columns])
    
    print("\n" + "=" * 50)
    print("FEATURE SUMMARY")
    print("=" * 50)
    print(f"Total number of enzymes: {len(df)}")
    print(f"\nCalculated features:")
    print(f"  - Basic physicochemical properties: {basic_count}")
    print(f"  - Thermostability features: {thermo_count}")
    print(f"  - Flexibility features: {flex_count}")
    print(f"  - Amino acid frequencies: {aa_features}")
    print(f"  - Amino acid group features: {group_features}")
    print(f"  - Dipeptide frequencies: {dp_features}")
    print(f"  ----------------------------------------")
    print(f"  TOTAL: {basic_count + thermo_count + flex_count + aa_features + group_features + dp_features}")

    # Note OGT if present
    if 'ogt' in df.columns:
        ogt_count = df['ogt'].notna().sum()
        print(f"\n  + OGT (Optimum Growth Temperature): available in {ogt_count} records")

    print("=" * 50)


def main():
    parser = argparse.ArgumentParser(
        description='Calculates enzyme protein features (TOMER-based)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python calculate_enzyme_features.py enzyme_data.csv
  python calculate_enzyme_features.py enzyme_data.csv -o features.csv
        """
    )

    parser.add_argument('input_file', help='Input CSV file')
    parser.add_argument('-o', '--output', default=None,
                        help='Output file (default: [input]_features.csv)')
    
    args = parser.parse_args()
    
    # Determine output file name
    if args.output:
        output_file = args.output
    else:
        base_name = args.input_file.rsplit('.', 1)[0]
        output_file = f"{base_name}_features.csv"
    
    print("=" * 50)
    print("ENZYME FEATURE CALCULATION (MODULAR)")
    print("Library: enzyme_feature_lib")
    print("=" * 50)
    
    # 1. Load CSV
    df = load_csv(args.input_file)
    
    # 2. Calculate features using the library
    # batch_process_dataframe function handles all loops and cleanup
    result_df = elib.batch_process_dataframe(df, sequence_col='sequence', verbose=True)
    
    # 3. Round results (Formatting)
    print("\nFormatting results...")
    
    # Rounding lists
    aa_cols = [f'aa_{aa}' for aa in elib.AMINO_ACIDS] # Get constants from the library
    basic_4_decimal = ['gravy', 'aromaticity', 'charge_density', 
                       'helix_fraction', 'turn_fraction', 'sheet_fraction',
                       'flexibility_mean', 'flexibility_std', 'flexibility_max', 'flexibility_min',
                       'boman_index', 'farias_bonato_ratio', 'arg_lys_ratio', 'acidic_basic_ratio']
    basic_2_decimal = ['molecular_weight', 'instability_index', 'isoelectric_point',
                       'charge_pH4', 'charge_pH7', 'charge_pH10', 'aliphatic_index']
    
    for col in result_df.columns:
        # Dipeptides (6 decimal places)
        if col.startswith('dp_'):
            result_df[col] = result_df[col].round(6)

        # Amino acids, groups and some basic features (4 decimal places)
        elif col in aa_cols or col.startswith('group_') or col in basic_4_decimal:
            result_df[col] = result_df[col].round(4)

        # Other physicochemical features (2 decimal places)
        elif col in basic_2_decimal:
            result_df[col] = result_df[col].round(2)
    
    # 4. Save results
    result_df.to_csv(output_file, index=False, sep=';')
    print(f"Results saved: {output_file}")

    # 5. Print summary
    print_summary(df, result_df)

if __name__ == "__main__":
    main()